### ISSUE TITLE
[FEATURE] vollständiges Tracking eingehender und ausgehender Zahlungen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2437]
Ziele:

- vollständiges Tracking eingehender und ausgehender Zahlungen

Mit dem Aktenkonto ist das Nachverfolgen eingehender Zahlungen bereits möglich, die Pflege der Daten aber nicht automatisierbar - bspw. durch Import eines Kontoauszuges (siehe #2236 ).

Ausgehende Zahlungen können derzeit nur rudimentär erfasst und nachverfolgt werden, bspw. durch Anlage eines separaten Belegtyps und dem Hinzufügen eines Dokuments zu diesem Beleg. Jedoch passt dann das Statusmodell des Beleges nicht und es fehlen Metadaten (bspw. Zahlung per... oder das Vorbereiten von Zahlungen und deren spätere Ausführung).

Dieses Ticket soll ein Konzept dafür beschreiben. 

**Grundlagen**

- Aktenkonto dokumentiert nur echte Geldbewegungen

**Zahlungsausgang**

- [x] neuer Tab "Zahlungen" in den "Finanzen" einer Akte
- [x] Datenmodell
- [x] Services
- [x] UI-Aktionen: erstellen, löschen, doppeln, bearbeiten, auflisten/anzeigen
- [x] Tab enthält eine Liste vorbereiteter Zahlungen, wobei eine Zahlung besteht aus: Zahlungsnummer (ähnlich Rechnungsnummer), Namen, Beschreibung intern, Beschreibung extern / Verwendungszweck, Empfänger (über Beteiligte der Akte), Betrag, Datum (optional, zwecks Terminierung von Zahlungen), Status (**Entwurf** - vorbereitet zur Zahlung, **freigegeben** - zur Zahlung freigegeben / Eingangsdatenmenge für Erzeugung einer SEPA-Überweisung, **veranlasst** - SEPA-XML exportiert oder anderweitige Veranlassung der Zahlung, **ausgeführt** - gesetzt manuell oder durch Import eines Kontoauszuges, **fehlgeschlagen**, , **storniert**), Datum der Veranlassung, veranlassende Person, Referenz zu Beleg, Referenz zu Zahlungsart
- [ ] ähnlich zu Bildungsvorschriften für Dateinamen: Betreffangaben der Zahlungen konfigurieren können
- [x] Option 1: manuelle Erstellung einer ausgehenden Zahlung
- [x] Option 2: Erstellung einer ausgehenden Zahlung aus Aktenkontobuchung (bspw. Auszahlung von Fremdgeld); Hinweis: eine eingehende Fremdgeldzahlung wird oft in mehrere Zahlungsausgänge an unterschiedliche Empfänger gesplittet
- [x] Option 3: Erstellung einer ausgehenden Zahlung aus Beleg (bspw. Gutschrift nach Rechnungsstorno)
- [x] Auswertung: Zahlungen nach Status
- [x] zentrale Ansicht mit Anzeige aller Zahlungen: nach Status
- [x] zentrale Ansicht mit Anzeige aller Zahlungen: Möglichkeit der Freigabe von Zahlungen im Status "Entwurf"; 
- [x] zentrale Ansicht mit Anzeige aller Zahlungen: Möglichkeit des Exports in SEPA-XML oder andere Formate (je nach Zahlungsart), für alle Zahlungen die "freigegeben" sind; mit Export den Status auf "veranlasst" setzen, Veranlassungsdatum und veranlassende Person setzen. Siehe #1420 - es müssen bei einem Export ggf. mehrere XMLs erstellt werden - eine pro Konto.
- [x] Prüfung auf offene Zahlungen bei Aktenablage

Frage: 

- werden für Auszahlungen von Fremdgeldern Belege erstellt? Dann könnte man Option 2 oben weglassen. Man erhält eine Rechnung und ist zur Zahlung angehalten. In diesem Fall könnte ein Beleg eines dedizierten Belegtyps erstellt werden. Das erhaltene Rechnungsdokument wird mit dem Beleg verknüpft / hochgeladen. Es gibt ein Fälligkeitsdatum (aus der Rechnung). Nutzer hinterlegt Status (Vorschlag für Statusmodell siehe unten) und kann eine Zahlungsart (bspw. "Überweisung von Konto xyz" oder "Paypal-Account abc") auswählen. Eine Buchung im Aktenkonto findet zu diesem Zeitpunkt nicht statt, sondern erst wenn ein Import des Kontoauszuges stattfindet und dort die Bezahlung dieser eingegangenen Rechnung "erkannt" wird.
- Konzept "Zahlungsnummer" prüfen - es wird irgendeine eindeutige ID für die automatische Verbuchung benötigt.

**Zahlungseingang, Automatisierung**

- [x] Import aus Kontoauszug
- [x] Suche nach Belegnummer
- [x] Suche mittels Jaro Winkler-Distanz (bspw. wenn Verwendungszweck bestimmte Zeichen nicht erlaubt - exakte Suche könnte öfters fehlschlagen)
- [x] Vorschlagliste für automatische Verbuchung, inklusive Aktenkontoeintrag, Belegstatuswechsel
- [x] klären: Zahlungen, die übersprungen / nicht verarbeitet werden, bei nächstem Import erkennen

**Zahlungsausgang: Automatisierung**

- [x] Import aus Kontoauszug
- [x] Suche nach Belegnummer oder Zahlungsnummer
- [x] Suche mittels Jaro Winkler-Distanz (bspw. wenn Verwendungszweck bestimmte Zeichen nicht erlaubt - exakte Suche könnte öfters fehlschlagen)
- [x] Vorschlagliste für automatische Verbuchung, inklusive Aktenkontoeintrag, Belegstatuswechsel, Zahlungsstatuswechsel

**Zahlungsausgang: Zahlungsarten** (keine ninjas-Anforderung)

Konfiguration der Zahlungsarten

- [ ] zentrale Konfiguration, analog Belegtypen
- [ ] Name, Beschreibung, Typ, optional ein Limit für darüber gezahlte Beträge
- [ ] Typ "Banküberweisung": Bank, BIC, IBAN, Kontoinhaber
- [ ] weitere Typen nach Bedarf - Stammdaten jeweils typspezifisch variierend - **was wäre hier noch relevant?**
- [ ] Nutzerverwaltung: pro Nutzer die Erlaubnis pflegen, welche Zahlungsarten vom jeweiligen Nutzer verwendet werden dürfen - analog bspw. der Rechnungsnummernkreise

**Fragen**

- mehrere Bankkonten pro Adressbucheintrag ermöglichen: nicht benötigt
- weitere Zahlungsinformationen an einem Adressbucheintrag ermöglichen? nein
- Berechtigungen? separate Rolle für Finanz-/Buchhaltungsfunktionen
- Erweiterung der aktuellen Dokumentenverknüpfung für Belege: mehrere Dokumente pro Beleg ermöglichen?
- Handhabung Belegart für ausgehende Zahlungen? nicht notwendig

neuer Belegtyp "erhaltene Rechnung" (Name ist unglücklich - etwas besseres finden - im Moment für das Verständnis aber hilfreich) -  (keine ninjas-Anforderung)

- [ ] neuer Belegtyp
- [ ] neuer Sub-Tab in "Finanzen" der Akte - Eingang und Ausgang sollten voneinander getrennt dargestellt werden
- [ ] Rechnungsnummer frei editierbar (kommt ja "von außen")

**Comment by j-dimension** [comment]
altes Konzept vom Mai 2024: 

Ziele:

- vollständiges Tracking eingehender und ausgehender Zahlungen

Mit dem Aktenkonto ist das Nachverfolgen eingehender Zahlungen bereits möglich, die Pflege der Daten aber nicht automatisierbar - bspw. durch Import eines Kontoauszuges (siehe #2236 ).

Ausgehende Zahlungen können derzeit nur rudimentär erfasst und nachverfolgt werden, bspw. durch Anlage eines separaten Belegtyps und dem Hinzufügen eines Dokuments zu diesem Beleg. Jedoch passt dann das Statusmodell des Beleges nicht und es fehlen Metadaten (bspw. Zahlung per... oder das Vorbereiten von Zahlungen und deren spätere Ausführung).

Dieses Ticket soll ein Konzept dafür beschreiben. 

**Zahlungseingang, Automatisierung der Aktenkonto-Eintragungen**

- [ ] Umsetzung von #2236 für einen Import aus Kontoauszug

**Zahlungsausgang**

Man erhält eine Rechnung und ist zur Zahlung angehalten. In diesem Fall könnte ein Beleg eines dedizierten Belegtyps erstellt werden. Das erhaltene Rechnungsdokument wird mit dem Beleg verknüpft / hochgeladen. Es gibt ein Fälligkeitsdatum (aus der Rechnung). Nutzer hinterlegt Status (Vorschlag für Statusmodell siehe unten) und kann eine Zahlungsart (bspw. "Überweisung von Konto xyz" oder "Paypal-Account abc") auswählen. Eine Buchung im Aktenkonto findet zu diesem Zeitpunkt nicht statt, sondern erst wenn ein Import des Kontoauszuges stattfindet und dort die Bezahlung dieser eingegangenen Rechnung "erkannt" wird.

Konfiguration der Zahlungsarten

- [ ] zentrale Konfiguration, analog Belegtypen
- [ ] Name, Beschreibung, Typ, optional ein Limit für darüber gezahlte Beträge
- [ ] Typ "Banküberweisung": Bank, BIC, IBAN, Kontoinhaber
- [ ] weitere Typen nach Bedarf - Stammdaten jeweils typspezifisch variierend - **was wäre hier noch relevant?**
- [ ] Nutzerverwaltung: pro Nutzer die Erlaubnis pflegen, welche Zahlungsarten vom jeweiligen Nutzer verwendet werden dürfen - analog bspw. der Rechnungsnummernkreise

neuer Belegtyp "erhaltene Rechnung" (Name ist unglücklich - etwas besseres finden - im Moment für das Verständnis aber hilfreich)

- [ ] neuer Belegtyp
- [ ] neuer Sub-Tab in "Finanzen" der Akte - Eingang und Ausgang sollten voneinander getrennt dargestellt werden
- [ ] Rechnungsnummer frei editierbar (kommt ja "von außen")
- [ ] Rechnungsbetrag (total, Steuern - ggf. mehrere bei unterschiedlichen Steuersätzen?)
- [ ] neues Metadatum: Zahlungsart (Auswahl aus konfigurierten Zahlungsarten)
- [ ] Angabe Verwendungszweck für Zahlung (wird dann in Überweisungen o.a. genutzt)
- [ ] Erfassung von Details zum Zahlungsempfänger: Import Bankverbindung aus Beteiligten der Akte
- [ ] Erfassung von Details zum Zahlungsempfänger: manuelle Eingabe Bankverbindung (aus Rechnungsdokument) - **oder sollte das Anlegen eines Adressbucheintrages mit diesem Konto erzwungen werden?**
- [ ] Validierung von IBANs (syntaktische Validierung) im Beleg (bspw. bei manueller Eingabe)
- [ ] Validierung von IBANs (syntaktische Validierung) direkt im Adressbucheintrag
- [ ] Erfassung von Details zum Zahlungsempfänger: Paypal-Zahlungsempfänger (Mailadresse? was wird noch benötigt?)
- [ ] eigenes Statusmodell, bspw. "eingegangen", "formale Prüfung", "sachliche Prüfung", "freigegeben", "Zahlung geleistet", "Zahlung fehlgeschlagen"
- [ ] **unklar: Statusübergänge in der Aktenhistorie dokumentieren?**
- [ ] Erweiterung der aktuellen Dokumentenverknüpfung für Belege: mehrere Dokumente pro Beleg ermöglichen

Zahlungsautomatisierung: in Abhängigkeit der gewählten Zahlungsart wären Möglichkeiten der Automatisierung zu prüfen

- [ ] Banküberweisungen: SEPA-XML erstellen, siehe #1420 - kann dann im Banking importiert und ausgeführt werden. Es müssen bei einem Export also ggf. mehrere XMLs erstellt werden - eine pro Konto.
- [ ] Paypal: über API?

Auswertungen

- [ ] alle erhaltenen Rechnungen für einen bestimmten Zeitraum
- [ ] alle zur Zahlung freigegebenen Rechnungen
- [ ] überfällige Rechnungen (ausgehende Zahlungen): Fälligkeitsdatum ist abgelaufen, aber zu dieser Rechnung gibt es weder (1) einen Eintrag im Aktenkonto noch (2) wurde der Status auf "Zahlung geleistet" gestellt, oder es gibt Eintragungen im Aktenkonto, aber die kumulierten Werte entsprechen nicht der Rechnungsssumme.

Zahlungsausgang, Automatisierung der Aktenkonto-Eintragungen

- [ ] Umsetzung im Rahmen von / analog zu #2236 für einen Import aus Kontoauszug - abweichend sind hier nur die Suche nach dem passenden Beleg und die Buchung im Aktenkonto als Zahlungsausgang statt Zahlungseingang
- [ ] benötigt separaten Dialog
- [ ] **mit Export eine Information am jeweiligen Beleg speichern, dass bereits exportiert wurde?**

**Fragen**

- mehrere Bankkonten pro Adressbucheintrag ermöglichen?
- weitere Zahlungsinformationen an einem Adressbucheintrag ermöglichen?
- Berechtigungen?

**Comment by j-dimension** [comment]
IBAN-Validierung: 

`boolean valid=SEPAValidatorIBAN.isValid("DE8570120400 8494547007");`
